### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by dylanhughes15** [dylanjeffries/elite-mission-tracker#1]
**Normal Priority**
None

**Lower Priority**
- [ ] Error Log
- [ ] Event Feed
- [ ] Custom section ordering

**Done**
- [x] Mission Redirected event colours mission light green
- [x] Mission Completed event removes mission
- [x] Mission Abandoned event removes mission
- [x] Manual start/stop timer
- [x] Collapsible sections
- [x] Move the Progress Bar to its own section
- [x] Make a new section for finances (Mission Rewards, Bounty Rewards, Averages)
- [x] Options menu for specific actions
- [x] Mission Board refresh alert when docked
- [x] Missions Progress Bar
- [x] Timer Reminders
- [x] "Loading Data" Overlay
